const drugsData = [
  {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.51837550300007, 0.9542577320000305],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.60963797600004, 0.8486280260000285],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.56272307100005, 0.7925726740000414],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.65219359900004, 0.8652593270000466],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.59555892300006, 0.9022018900000717],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.57764291100005, 0.8843667320000463],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.53365537600007, 0.992848843000047],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.54160774800005, 0.9611185510000269],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.51974101500008, 0.9303937030000498],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.44614521200003, 0.9524813800000516],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.46718114100008, 0.8995797400000356],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.49310412500006, 0.8767942270000617],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.43989564700007, 0.9477543980000291],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.26213451900009, 0.8506863230000477],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [104.62177495400005, 0.9935712940000485],
        },
        properties: {
          NAMOBJ: "",
          FCODE: "",
          LCODE: "GI0020",
          SRS_ID: "",
          REMARK: "Puskesmas/Puskesmas Pembantu",
          METADATA: "",
          KWKPKM_: 0,
          KMPPKM_: 0,
          JPLPKM_: 0,
          PKMKODE_: "",
          PKMKAT_: 0,
          PKMLMT_: "",
        },
      },
    ],
  },
];
